### Qualitative examples for each metric
pkl -> UniEval coherence

csv -> bartscore

json -> GPT4 evaluations

In [2]:
import pandas as pd

#### UniEval coherence

In [40]:
df = pd.read_pickle('/workspaces/lit-gpt/out/inference/pythia-160m-deduped-sharegpt-base-eval.pkl')
df.describe()

,naturalness,coherence,engagingness,groundedness,understandability,overall
count,5267.000000,5267.000000,5267.000000,5267.000000,5267.000000,5267.000000
mean,0.351654,0.623490,8.080900,0.735613,0.347106,2.027753
std,0.299444,0.363078,14.981729,0.305731,0.301235,3.019186
min,0.000095,0.000070,0.000164,0.000514,0.000081,0.005258
25%,0.089707,0.264873,0.861148,0.538258,0.085722,0.524865
50%,0.264645,0.766236,2.557401,0.889961,0.256035,0.975080
75%,0.571763,0.961410,10.971905,0.975499,0.566658,2.635667
max,0.999912,0.999846,450.413199,0.999944,0.999917,90.768890

In [83]:
df

,input,output,label,naturalness,coherence,engagingness,groundedness,understandability,overall
0,"I am making mayonnaise, it was starting to thi...","Nothing, hasnothing, isnothing, isnothing, doe...","Yes, it's possible to fix runny mayonnaise! Th...",0.068879,0.005465,0.036438,0.366695,0.068096,0.109115
1,What is optimal Mayonnaise thickness?,]. ## From the Online Instructional Video Wh...,The optimal mayonnaise thickness will depend o...,0.111042,0.211688,2.023898,0.854118,0.111710,0.662491
2,"I am making mayonnaise, it was starting to thi...","ziemzaza zaunikasannia se zabauza obytojni, zn...","Yes, it's possible to fix runny mayonnaise! Th...",0.036620,0.049723,0.012429,0.768196,0.036118,0.180617
3,What is optimal Mayonnaise thickness?,")? Chop-up-the-chop, the new or the old. Hav...",The optimal thickness of mayonnaise can vary d...,0.154121,0.608273,1.015807,0.983253,0.117305,0.575752
4,"I am making mayonnaise, it was starting to thi...",", may be, Teddy I am a student at Berkeley C...","Yes, it is possible to salvage your mayonnaise...",0.129091,0.433045,0.586473,0.955527,0.123747,0.445577
...,...,...,...,...,...,...,...,...,...
1680,Does this mean that Into the Breach is a game ...,?Or?And?In a game with a better better story?A...,A game is broadly considered to be perfect inf...,0.471146,0.077505,50.285279,0.770567,0.506659,10.422231
1681,I've recently started playing the turn-based s...,它 [2] When you reach the point of your first ...,"In the context of Into the Breach, ""perfect in...",0.762709,0.993709,11.326418,0.999303,0.861076,2.988643
1682,Does this mean that Into the Breach is a game ...,?Or is it just a game of perfect information?T...,"Yes, even though there is a lot of strategy in...",0.068524,0.625953,13.947606,0.869565,0.065486,3.115427
1683,I've recently started playing the turn-based s...,名称](http://en.wikipedia.org/wiki/File:File:Fil...,"In the context of Into the Breach, ""perfect in...",0.439139,0.012811,0.029742,0.222352,0.423337,0.225476
1684,Does this mean that Into the Breach is a game ...,: has: is: is: is: is: is: is: is: is: is: is:...,Depends. Does the game feature a line of sigh...,0.052499,0.081561,0.602606,0.633863,0.045847,0.283275

In [3]:
df.coherence.mean()

0.9014245388724036

In [5]:
df.sort_values(by='coherence').tail(10)[['input', 'output', 'coherence']].values

array([["Why don't people like the many-worlds interpretation of quantum mechanics?",
        'Yes, the many-worlds interpretation of quantum mechanics is a complex and multifaceted field. It is often used to explain the laws of physics, which allow for the existence of quantum systems in a way that would be impossible without the existence of the large scale objects. However, quantum mechanics is not meant to be taken literally. It is a philosophical and practical approach that aims to explain and interpret quantum systems.\n\nThe multiple-worlds interpretation of quantum mechanics is a complex and multifaceted approach that seeks to understand the laws of physics and the behavior of quantum systems. It is a departure from the more idealistic interpretations of quantum mechanics that were used by philosophers such as Bertrand Russell and Thomas W. Thorne.',
        0.999531],
       ['Can you list the issues with using a symmetric probability distribution when modelling problems?',
        'The reason is that while symmetric probability distributions can be useful for some problems, they can fail to capture all the possible events of interest. In particular, symmetric probabilities can lead to inconsistent or incorrect results. For example, if you have a set of events that could lead to the same outcome, then you could be unable to capture the events that lead to the opposite outcome, even if they are not known beforehand.\n\nIn general, the answer to this question depends on the specific problem you have in mind. As an example, consider a system where you have a set of events, each occurring in a sequence of events, and consider a transition between these events. For example, you could have a system where you want to find the probability of transitioning between events, and then look at the transition probabilities of each event.\n\nThe choice of solution depends on the specific problem you have in mind. For example, you could look at the probability distributions of the probabilities of transitioning between events and then look at the transition probabilities of each event. In this case, the probabilities of transitioning between events and then evaluating the probability of transitioning between events are not known beforehand.\n\nIt is important to note that if you are trying to model problems that are not known beforehand, you may not be able to capture all possible events. For example, if you have a system where you have a set of events, and you want to make decisions about the outcomes of the events, then you could model problems that are outside of your control.',
        0.999569],
       ['Can you give me a summary of all the important historical events that took place on that date?',
        "The Roman and Byzantine emperors of Constantinople (381-270 BC) had a complex relationship with each other, as well as with their respective emperors and their respective cultural backgrounds. However, the most significant historical events that took place on that date were the Battle of Agathoc too soon after the fall of Constantinople.\n\nWhile the Roman Empire saw significant military victories and invasions, it also faced a number of challenges, including the loss of key cities, the decline of the Eastern Rift, the weakening of the Silk Road, and the collapse of the Iron Age.\n\nOverall, the Roman Empire faced a number of challenges, including the rise of the empire's economic power, the spread of empires, and the eventual collapse of the Eastern Rift. However, the most significant historical event that took place on that date was the Battle of Agathoc which was fought between the Byzantines and the Byzantines.\n\nDuring the Battle of Agathoc, the two armies met in a central square to form a potential future union. Aftermath:\n\n* Battle of Agathoc, a major battle involving the combined armies of the two cities, battles with the Byzantines, and the defeat of the latter two cities.\n* Battle of Agathoc, a major battle involving the Byzantines and the Byzantian Empire.\n* Battle of Agathoc, a major battle involving the Byzantines and the Romans.\n* Battle of Agathoc, a major battle involving the Byzantines and the Romans.\n\nOverall, the Roman and Byzantine emperors faced a number of challenges, including the rise of the Eastern Rift, the fall of the Iron Age, and the weakening of the Western Roman Empire.",
        0.99959],
       ['ok, perfect. what tools can we use for enhancing the managerial performance? give me some tools for each point you provided. for example I know that I can use Microsoft Project for project managing.',
        'The following are some suggestions for enhancing the managerial performance:\n\n1. Use the "check" feature, which allows you to keep track of your progress throughout the day. You can use the "check" feature to check all your daily tasks and make sure you are doing the things that the manager should do to complete your tasks.\n\n2. Use the "max" feature, which allows you to limit your work to a certain number of tasks, causing the manager to stop and prioritize tasks that are most important to you. You can use the "max" feature to limit the number of tasks to a certain number, but keep the limit to a certain number.\n\n3. Use the "work" feature, which allows you to search for specific tasks that you need done and prioritize them based on your needs. For example, you can search for "tasks to complete" and "tasks to complete" by clicking on the "tasks" tab.\n\n4. Use the "spam" feature, which allows you to check your daily tasks and make them skip when they are not needed or when they are not needed. You can use the "spam" feature to check your weekly tasks and make sure you are not missing any important tasks.\n\nHere are some suggestions for enhancing the managerial performance:\n\n1. Keep in mind that there are many managerial processes and tasks that require more time, such as managing projects or prioritizing tasks. You can choose to prioritize tasks based on their importance, rather than the urgency of the task.\n2. Keep in mind that while you can improve the managerial performance by improving the efficiency of the process, it is important to ensure that the process is well-maintained and accurate.\n\n3. Use the "max" feature, which allows you to limit the number of tasks you can run to when you need to prioritize tasks and to get the most out of your work.\n\n4. Look for areas where you can improve the managerial performance by incorporating additional features or activities into your daily tasks. For example, you can include features such as "watch" and "tasks" in your daily tasks to improve their performance and to add additional activities.\n\n5. Use the "work" feature, which allows you to keep track of your tasks and prioritize tasks based on their importance. For example, you can keep track of your tasks based on the importance of one task and to avoid being overwhelmed by the task if you',
        0.999594],
       ["The Second Amendment guarantees citizens' ability to own and operate firearms. The ATF restricts people's ability to do so, and may even punish people for violating its regulations. Isn't the ATF's restriction of firearm ownership a violation of the Second Amendment?",
        'The Second Amendment guarantees individuals the right to possess firearms and that they have the right to possess that they possess. The ATF has the power to restrict firearms to an unlimited number of individuals without regard to their individual rights. The right to possess firearms is not a fundamental right and is restricted to individuals. The ATF has the power to enforce its laws and to protect its citizens from dangerous and uncooperative individuals. It has the power to limit firearms to certain categories, such as those who possess firearms without the express written consent of the ATF. The right to possess firearms is not a right and it is a civil right and can be subject to legal restrictions. All individuals possess firearms, including anyone who owns or operates them.\n\nIt is important to note that the Second Amendment is a fundamental right and should not be taken lightly. It is a fundamental right that individuals possess and that they have the right to possess firearms. The right to possess firearms is not a fundamental right and is limited to individuals. It is a fundamental right of every citizen and that individuals have the right to keep and bear Arms. The right to possess firearms is not a fundamental right and is subject to laws and regulations.',
        0.999604],
       ["Can you tell me, in layman's terms, how the solution to the Taniyama–Shimura–Weil conjecture, also known as the Modularity Theorem, lead to the proof of Fermat's Last Theorem?",
        "The Taniyama–Shimura–Weil conjecture is a conjecture in the theory of elliptic curves, which is a conjecture due to Chen, Ting, and Zhang to the Tutte Conjecture. It is one of the most famous conjectures in the theory of elliptic curves and has been proven by Lin and Wang in a series of papers. The Taniyama–Shimura–Weil conjecture is known to hold true for elliptic curves with complex coefficients, which is known to have a unique solution.\n\nThe modularity conjecture is a conjecture of Pascal, which is a conjecture of the Euler characteristic of the space of algebraic integers. It was first proposed by Lin in 1822 and has since become a well-known problem in the theory of algebraic number theory.\n\nIn general, the more general form of the Fermat–Weil conjecture is not known, although it has been proven to be true in a few cases. It has been conjectured to have a unique solution to the Taniyama–Shimura–Weil conjecture, which is known to have been proven by Chen, Ting, and Zhang in a series of papers. However, it is not known whether it has a unique solution to the Euler-Veech equation.\n\nIn addition to the Fermat-Weil conjecture, there are also other conjectures that have been proposed:\n\n1. Fermat's Last Theorem: The conjecture is a conjecture due to Chen, Ting, and Zhang that was first proposed by Lin and Wang in a series of papers in the field of algebraic number theory. It has been proven to have a unique solution to the Euler-Veech equation, which has been confirmed by Liu and Wang in a series of papers.\n\n2. Fano Conjecture: The conjecture is a conjecture of the Fermat-Weil conjecture, which is a conjecture due to Chen, Ting, and Zhang to the Tutte Conjecture, which is a conjecture related to the Fermat-Weil Conjecture. It is a conjecture that has been conjectured to have a unique solution to the Euler-Veech equation, which has been confirmed by Liu and Wang in a series of papers.\n\n3. Fermat's Last Theorem: The conjecture is a conjecture that was first proposed by Lin and Wang in a series of papers in the field of algebraic number theory. It has been proven to have a unique solution to the Euler-Vee",
        0.999609],
       ['Thank you.  Is it better to build my own PC or to just buy one off the shelf?  Give me the pros and cons of each approach.',
        'Building a PC is a complex process, and ultimately the selection of components and hardware can vary based on your needs. Some components may be more customizable, while others may be more difficult to upgrade or modify. Another factor to consider is the overall cost of the machine.\n\nHere are some pros and cons of each approach:\n\n1. The cost of the machine could be more expensive compared to the cost of the hardware. The cost of a machine can vary based on the type of hardware and the price of the machine.\n2. The cost of the machine could be lower if you are not using a specific brand of the machine.\n3. The price of the machine could increase or decrease with the price of the hardware.\n4. The size of the machine, such as the size of the screen, can also be added to the cost of the machine.\n5. If you are not using a specific brand of the machine, the price of the machine may be more expensive compared to the cost of the hardware.\n6. The cost of the machine may be lower if you are using a specific brand of the machine.\n7. There is more customization needed to create the machine. For example, you might want to modify the hardware to account for different screen sizes and other features.\n\nOverall, the choice of approach can vary depending on the specific needs and requirements of each solution. It is usually recommended to choose the right approach based on the specific needs and requirements of your specific solution.',
        0.999646],
       ['Hi, can you tell me a story in a novel format including dialogs between the characters, a story based on the Justice League comics, including the characters, Green Arrow, Red Arrow and Cheshire.',
        'Sure, here\'s a story in a novel format that follows the Justice League, a group of heroes battling off against time-travelers and a waterworld villain known as the Green Arrow:\n\nThe Justice League is a mysterious, alternate-day fighting game that takes place in a distant land called Greenland, and where they fight against time travelers and fight off death and misfires.\n\nIn this game, players take on the role of the Justice League, a mysterious, multiverse-driven game that is played by a team of seven unique and sometimes incompatible characters. With each encounter, the players must navigate their way through a series of challenges and obstacles, with each character battling against time and facing off against the cosmic forces that shape the world they play.\n\nThroughout the game, players are given unique and complex challenges to navigate, with each encounter leading to new challenges and obstacles. The heroes and villains battling to survive and defeat the cosmic forces, while battling for the love of their own, ultimately leading to the end of the game.\n\nIn this highly competitive game, players must navigate through a multiverse of challenges and obstacles, with each encounter challenging them to overcome the challenges and overcome them. The team must also face the dark forces of time and the forces of darkness, with each encounter challenging them to find their own way back to their own world.\n\nEach character has their own unique challenges and obstacles, with each encounter, the heroes and villains battling for the right to control the game and control the future of the game itself. The team must navigate through a series of challenges and obstacles, with each encounter challenging them to overcome the challenges and overcome them.\n\nUltimately, the story of the game is a journey of discovery and the characters in it explore a unique and complex world that will take them on a journey of creating a better future for all. It\'s up to each of the team to create a unique and complex game of their own, and it\'s up to each of us to bring it to life.\n\nIn this story, the story unfolds in a unique and complex world where players face the challenges of time travel, conflicted emotions, and the clash of cultures. Along the way, players face the challenges of identity, identity, and the future of the world they play.\n\nIn "Justice League," the team must navigate through a multiverse of challenges and obstacles, with each encounter facing off against the cosmic forces that shape the world they play. The team must navigate',
        0.999663],
       ['Write an essay on how Romeo is most to blame for the events that take place in the end of the book,',
        'The Roman Emperor built a huge, double-decker bus that he used to transport his troops to the cities of the East. In the summer of 44 AD, the Roman fleet was being sunk by a British frigate, which had been sunk by a German frigate, making it impossible to advance. The Romans had been sailing for long periods of time without any warning from the British. The strike was met with great resistance by the German fleet, which was soon defeated by the Romans. The Romans had to fight back, with all their might, with all their might. However, the fate of the empire ultimately came to a head after the defeat of the Roman Empire, when the Roman fleet was overwhelmed by the German ships, the Guards of Italy.\n\nThe Romans were unhappy with the situation, and decided to turn to the use of force. They had to use their armies wisely and effectively, with the soldiers in tow. They launched all of their forces on the front lines, and they were met with overwhelming resistance. They responded by sending their best soldiers home, believing that the Romans were completely at fault.\n\nThe Romans were deeply unhappy with the outcome of the war, and they were determined to make it right and quickly defeat the Byzantines. They used their ships, tactics, and weapons to the utmost, and they used their military machine to execute their demands. They used their military advantage to their advantage, and they used their ships to the utmost to take down the enemy fleet.\n\nThe Roman Empire had faced a series of challenges, with the most major one being its invasion of the West African empire. The Roman fleet had been making steady progress since the end of the Arab conquest, but it was now setting up an offensive campaign to destroy the Byzantines.\n\nThe Roman defeat at the end of the war was a test of their ability to adapt to the new situation, as it put an end to the barbarian invasions. They had to make the most of their own resources and bestow them with military might, including the right to defend themselves in case of rebellion or to seize control of the cities of the East. The Romans had to adapt to the new situation, with their ships and equipment, and they faced a full-fledged threat from the Byzantines.\n\nThe defeat of the Roman Empire was a test of their ability to adapt to new situations and to defeat the Western Empire. However, the defeat of the Roman Empire was not without its consequences. The Roman fleet had been',
        0.999731],
       ["Yes it is, but it's still too long for a brief summary. Can you shorten it a bit? Around 20% shorter than it is now, please.",
        "Sure, I can shorten it as long as it is still at the same level. But it still feels like it's been a long time since I last saw it.\n\nThe time it took to get to the end of the song is when you said you were going to see it again (it was the shortest time of my life). You could also tell me about the time you visited the beach, but feel free to tell me about it. But the time it took to get there was closer to the end.\n\nAnyway, here is a rough draft of the song:\n\nVerse 1:\n\nI love the way you speak, and I feel like you're talking to me. You sound like you're talking to me\n\nChorus:\n\nIt's been a long time since I saw the ocean, but I've been dreaming of it\n\nChorus: I'm dreaming of the ocean, and I'm doing it\n\nBridge: I'm dreaming of the ocean, and I'm doing it\n\nVerse 2:\n\nI love the way you talk, and the way you hold yourself. I love the way you talk, and I feel like you're there with me\n\nChorus: I'm dreaming of the ocean, and I'm doing it\n\nBridge: I'm dreaming of the ocean, and I'm doing it\n\nVerse 3:\n\nI love the way you talk, and the way you hold yourself\n\nChorus: I'm dreaming of the ocean, and I'm doing it\n\nBridge: I'm dreaming of the ocean, and I'm doing it\n\nChorus: I'm dreaming of the ocean, and I'm doing it\n\nBridge: I'm dreaming of the ocean, and I'm doing it\n\nBridge: I'm dreaming of the ocean, and I'm doing it\n\nBridge: I'm dreaming of the ocean, and I'm doing it\n\nBridge: That's the longest time I've been dreaming about the ocean, and I'm doing it\n\nBridge: It's the longest time I've been dreaming about the ocean, and I'm doing it\n\nBridge: It's the longest time I've been dreaming about the ocean, and I'm doing it\n\nBridge: It's the longest time I've been dreaming about the ocean, and I'm doing it\n\nBridge: It's the longest time I've been dreaming about the ocean, and I",

#### BartScore

In [34]:
df = pd.read_csv('/workspaces/lit-gpt/out/inference/pythia-410m-deduped-oasst1-final-eval.csv')

In [5]:
df.dropna(subset=['BARTScore']).sort_values(by='BARTScore').tail(5)[['input', 'output', 'BARTScore']].values

array([['What are the five most common causes of stress among people?',
        'how how how how how how how how to use to for building of of the of the of the of the of the of the of the of the of the of the of the of thea of theof the of the of the of theof the of the of the of thea of theof the of theof theof thea of theof the of theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theoftheof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof thetheof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof theof the',
        -0.8667047023773193],
       ["What's the furthest back we can prove human existence? Is there good reason to believe it goes further then this point?",
        'Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework Framework ',
        -0.6490703225135803],
       ['Has the US National Reconnaissance Office ever confirmed the existence and capabilities of the KeyHole satellites?',
        'Is the number of the unicode char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char symbol char char charchar char char __char char char[0]; char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char char[_ char char char char char char char char char char char char char char char char char char char char char char char char char char char char char',
        -0.5634528994560242],
       ['is javascript back end or front end language?',
        ' language? The language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the languages of the languages of the languages of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of the language of',
        -0.5209837555885315],
       ['can you write haiku for different inductive biases in deep learning models? start with attention',
        ' and how do you write a simple fine sense of fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine, fine fine fine fine fine fine fine fine fine fine, fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine, fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine. Fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine, fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine, fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine\nfine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine fine',
        -0.4356985986232757]], dtype=object)

### Themis

In [39]:
from output_themis import THEMIS_ASPECTS
import json

filename = '/workspaces/lit-gpt/out/themis_out/evaluation_pythia-1.4b-deduped-oasst1-final-eval.json'
data = json.load(open(filename))
rows = [{'id': i // 4, 
            'metric': THEMIS_ASPECTS[i % 4].split(':')[0],
            'analysis': row['Evaluation Outputs'][0]['Analysis'],
            'rating': row['Evaluation Outputs'][0]['Rating']
            } for i, row in enumerate(data['Evaluation'])]

df = pd.DataFrame(rows).set_index('id')

In [40]:
data_df = pd.read_pickle(filename.replace('themis_out/evaluation_', 'inference/').replace('.json', '.pkl'))

In [41]:
df

,metric,analysis,rating
id,,,
0,Context Maintenance,The response provided is a valid continuation ...,5.0
0,Interestingness,The response provided is quite informative and...,4.0
0,Knowledge Use,The response demonstrates a good use of knowle...,5.0
0,Naturalness,"The response provided is natural and coherent,...",5.0
1,Context Maintenance,The response provided is a valid continuation ...,5.0
...,...,...,...
1683,Naturalness,The response provided is a detailed and natura...,5.0
1684,Context Maintenance,"The response ""Yes."" directly addresses the que...",5.0
1684,Interestingness,"The response ""Yes."" is very brief and lacks an...",1.0
1684,Knowledge Use,"The response ""Yes."" is direct and to the point...",3.0
1684,Naturalness,"The response ""Yes."" is direct and to the point...",5.0

In [42]:
df = df.groupby('metric').apply(lambda x:x).rating.unstack(level=0).join(data_df)

/tmp/ipykernel_6055/1413054046.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df = df.groupby('metric').apply(lambda x:x).rating.unstack(level=0).join(data_df)

In [37]:
df[df.output.str.strip() == df.label.str.strip()][['input', 'output']]

                                  input                                 output
id
1398  What is the capital of Australia?  The capital of Australia is Canberra.

In [48]:
df[df.groundedness > .9][['input', 'output']]

,input,output
id,,
4,"I am making mayonnaise, it was starting to thi...","Yes, there are several ways to salvage mayonna..."
5,"I am making mayonnaise, it was starting to thi...","If your mayonnaise has turned liquid again, th..."
9,"I am making mayonnaise, it was starting to thi...",If your mayonnaise has become liquid and thick...
11,Can you help me understand how I can estimate ...,"To estimate the variance of a variable, we nee..."
12,Is variance the same as sum of squares error?,"Yes, variance is the same as the sum of square..."
...,...,...
1656,"In minecraft, what are the best ways to farm e...","In Minecraft, there are several ways to quickl..."
1660,Write out your thinking process when coming to...,Sure! Here's my thinking process: I first tho...
1669,Do you know a single person in the world who o...,The world's only working fighter jet is owned ...
1673,I've recently started playing the turn-based s...,The term 'perfect information' refers to a con...
1677,I've recently started playing the turn-based s...,This is a turn-based strategy game that is con...

In [52]:
df.sort_values(by='Context Maintenance').tail(10)[['input', 'output', 'label', 'Context Maintenance']].values

array([['In TypeScript, how can I tell the type system "I know that in theory this value may have these multiple types, but in practice I know it will only have this one"',
        'In TypeScript, the type system is known as "Existential type checking". In TypeScript, the type system is designed to check that a value does indeed have a certain type, and will not let you pass it by accident if the type checker can\'t prove that it actually has a certain type.\n\nTo tell the TypeScript type checker "I know that in theory this value may have these multiple types, but in practice I know it will only have this one type", you can use the "any" type constructor to specify that the type of a value must be able to hold any value of any type.\n\nFor example, if you have a function that takes a value of any type and returns a string, you can use the "any" type constructor to specify that the type of the value passed to this function must be "any" type.\n\nThis means that even if the TypeScript type checker can\'t prove that a value actually has a certain type, it still has to check that the value can be passed to the function without any type checking, which means that the value doesn\'t have to be of the specific type that the function was defined to accept.\n\nSo essentially, the type checker requires that the value passed to the function be able to hold any value of any type, even if the actual type doesn\'t match the type that you specified when defining the function.\n\nIn the example above, I have added the "any" type constructor to the signature of the function, which tells the TypeScript type checker that the value passed to the function must be able to hold any value of any type, even if the actual type of the value doesn\'t match the type that you specified when defining the function.\n\nSo with this added information, the type checker will know that it should not let you pass a value of the "int" or "string" type by accident, because it knows that the value could potentially hold other types as well, and it will not let you pass it by accident if the actual type of the value doesn\'t match the type that you specified when defining the function.\n\nNote: The "any" type constructor is a "type erasure" type constructor, which means that it creates a kind of "virtual" type which doesn\'t have to be explicitly instantiated by the programmer.',
        'TypeScript allows you to use union types based on several existing types (called member types). For example,  a function that works with strings or numbers could be defined as ```function printId(id: number | string)```.\n\nA value matches a union type if it matches any of the union type\'s members. In the given example, the first parameter to `printId` (that is, `id`) can be either `number` or `string`.\n\nTypeScript will only allow operations on a value of a union type in two conditions.\n(1) If it is valid for every member of the union, OR \n(2) If you write some code which allows TypeScript to deduce the specific type. For example, code in a conditional like ```if (typeof id === "string") {}``` can perform any operation that is valid on strings. In this way you can use code to tell TypeScript that certain code only applies when the value has one specific type. This is called "narrowing." You do not',
        5.0],
       ['How can I do this in Javascript?',
        "Here's an example in Javascript:\n\nconst id = 'id_' + Math.random();\nconst element = document.getElementById(id);\nelement.innerHTML = 'Hello, ' + element.innerHTML;\n\nIn this example, we use the 'getElementById' method to get the element with the id 'id_' + Math.random(). We then set its innerHTML to 'Hello, ' + element.innerHTML.\n\nYou can also use the HTML string concatenation operator + to create a new element with the specified innerHTML.\n\nSo in summary, you can create a new element with the id 'id_' + Math.random() and append it to the current element with innerHTML 'Hello, ' + element.innerHTML;",
        'In JavaScript, you can\'t directly specify a variable\'s type in the same way you can in TypeScript. However, you can achieve a similar effect by using type checking and type conversion techniques.\n\nTo specify that a value can have multiple types but you know it will only have one in practice, you can use type checking and type conversion techniques to enforce the expected type at runtime. Here\'s an example:\n\n        let value = "hello";\n        if (typeof value === "string") {\n          let length = value.length;\n          console.log(length); // Output: 5\n        } else {\n          console.log("Expected a string value.");\n        }\n\nIn this example, the value variable is assigned a string value. We can check the type of value using the typeof operator, and then conditionally access the length property only if value is a string. If value were anything else, such as a number or an object, the code would skip the if block and log an error message instead.\n\nThis technique isn\'t as powerful or expressive as TypeScript\'s type system, but it can still help catch certain types of bugs and make your code more reliable.',
        5.0],
       ['In TypeScript, how can I tell the type system "I know that in theory this value may have these multiple types, but in practice I know it will only have this one"',
        'In TypeScript, the type system can be thought of as a type-system that knows what types it will know in theory, but ignores types that it doesn\'t know in practice.\n\nTo tell the type system that you know that it can ignore types that it doesn\'t know in practice, you can use a type assertion. Here\'s an example:\n\n```ts\nconst value: string = "Hello world";\n\n// The type assertion tells the TypeScript compiler "I know that in theory this value\n// may have multiple types, but in practice I know it will only have this one."\n// We can then use the value variable in the code without worrying about the type.\n```',
        'TypeScript allows you to use union types based on several existing types (called member types). For example,  a function that works with strings or numbers could be defined as ```function printId(id: number | string)```.\n\nA value matches a union type if it matches any of the union type\'s members. In the given example, the first parameter to `printId` (that is, `id`) can be either `number` or `string`.\n\nTypeScript will only allow operations on a value of a union type in two conditions.\n(1) If it is valid for every member of the union, OR \n(2) If you write some code which allows TypeScript to deduce the specific type. For example, code in a conditional like ```if (typeof id === "string") {}``` can perform any operation that is valid on strings. In this way you can use code to tell TypeScript that certain code only applies when the value has one specific type. This is called "narrowing." You do not',
        5.0],
       ['Can you provided the mathematical formula for doing so? And a tenable example to help me understand.',
        'Sure! Calculating the velocity of a projectile using Pythagoras\' Theorem is a simple and common problem in mathematics. Here is the formula for calculating the velocity of an object moving with an acceleration of g:\n\nv = g/t^2\n\nLet\'s say you want to calculate the velocity of a projectile moving at a speed of 5 m/s. To do this, you would use the following formula:\n\nv = 5 / (t^2 * 2)\n\nIn this formula, "t" represents the time it takes for the projectile to travel the distance "d" (in this case, 5 m), and "v" represents the velocity of the projectile.\n\nTo understand this formula, let\'s look at an example. If we stop a projectile at (0,0), and then shoot it into the air at a speed of 5m/s, then the distance it has traveled through the air is 5m. This means that the time it has taken for the projectile to travel this distance is 2/5 seconds.\n\nThe formula for calculating the velocity of a projectile moving with an acceleration of g is:\n\nv = g/t^2\n\nNow, let\'s apply this formula to our example. If we shoot the projectile from (0,0) to (10,10), and then measure the distance it has traveled, we would get 10/2/5 = 4m.\n\nSo, we have a projectile with distance 4m moving 5m/s, or 0.05m/s.\n\nTo find the time it took for the projectile to travel this distance, we would use the following formula:\n\nt = (d/v)\n\nNow, let\'s plug in our values for "d" and "v":\n\nt = (4/0.05) = 2/0.05 = 1/10s\n\nSo, the time it took for the projectile to travel the distance of 4m is 1/10s.',
        'Sure. Formula for the variance of a variable is:\n\nVariance = E[(X - μ)^2] = E[X^2] - (E[X])^2',
        5.0],
       ['Can you help me understand how I can estimate the variance of a variable?',
        "You can estimate the variance of a random variable by finding the square root of its mean-square error. The mean-square error is the error that is made when estimating a random variable's value. If the true value is known, the square root of this error is simply the variance.\n\nHere's an example to help illustrate the formula:\n\nSuppose we want to estimate the value of a random variable X, which has a uniform distribution over the interval [0, 1]. We can use the following formula:\n\nvariance = (X - mean)^2 / m\n\nwhere m is the sample size.\n\nThe formula assumes that the random variable X has a normal distribution, which is a uniform distribution on a -1, 0, 1 interval. If the distribution is skewed, the formula may not hold.",
        'Sure, estimating the variance of a variable is a useful tool for measuring how much the values of a variable differ from the mean. The most common method for estimating the variance of a variable is to calculate the sample variance. This requires you to calculate the mean of the sample, and then subtract the mean from each value in the sample and square the result. The sum of these squared differences is then divided by the sample size minus one to get the sample variance. You can also estimate the variance of a population using the same method, but instead of dividing by the sample size minus one, you divide by the population size.',
        5.0],
       ["I've recently started playing the turn-based strategy game Into the Breach. I have read online that the game is considered to have 'perfect information'. What is meant by 'perfect information' in this context?",
        '"Perfect information" refers to the situation where all information about an event is known with 100% certainty. In other words, there is no uncertainty or doubt. In this sense, Perfect information is an idealized and hypothetical state that is not possible, but it is what many people assume Perfect information to be.',
        'In the context of Into the Breach, "perfect information" means that all information about the game state, including all future possible moves and their consequences, is available to all players at all times. This means that players have full knowledge of the game state, including the positions of all units and obstacles, and can make informed decisions based on that information.',
        5.0],
       ['Does this mean that Into the Breach is a game of perfect information?',
        'Yes, it does.',
        'Yes, even though there is a lot of strategy involved all information is available to all players at all times. Chess is another example of a perfect information game. Compare this to a game like Starcraft or League of Legends. In Starcraft each player has hidden information, in League each team does.',
        5.0],
       ["I've recently started playing the turn-based strategy game Into the Breach. I have read online that the game is considered to have 'perfect information'. What is meant by 'perfect information' in this context?",
        '"Perfect information" in this context refers to the information that is known to all parties in the game, including the player, the adversary, and the game engine. This is often described as "the best-case scenario." The game engine is trying to maximally exploit the information it knows and to maximize its own reward, which can only be achieved if it is able to fully anticipate the actions of the other players.',
        'In the context of Into the Breach, "perfect information" means that all information about the game state, including all future possible moves and their consequences, is available to all players at all times. This means that players have full knowledge of the game state, including the positions of all units and obstacles, and can make informed decisions based on that information.',
        5.0],
       ['Does this mean that Into the Breach is a game of perfect information?',
        'Yes.',
        'Depends.\n\nDoes the game feature a line of sight mechanic? Are the enemies able to conceal information, such as laying down hidden traps? These would disqualify it from being a Perfect Information game.\n\nDoes the game feature randomly generated damage? If so, is the probability distribution known to the player? Can the player see the results of the PRNG roll before executing a turn? This might also disqualify it, although some academics consider chance games with known probability distributions to be valid for analysis as Perfect Information games.\n\nAre turns executed simultaneously? If so, information required to formally reason about the current turn is hidden.',
        5.0],
       ['I am making mayonnaise, it was starting to thicken but now it has become runny and liquid again, is there any way to salvage it?',
        'To salvage mayonnaise that has become runny and liquid, you can add a small amount of oil to the mixture to help it thicken up. You can also use a whisk to blend the ingredients together, which can help to give it a smoother texture. You can also strain the mixture if it becomes too liquid, but this can be a time-consuming process. Lastly, you can eat the mayonnaise as is, but it will not be as good as when it is well-made, as it will lose some of its deliciousness.',
        "Yes, it's possible to fix runny mayonnaise! The most common reason for mayonnaise becoming runny is because the oil was added too quickly or the egg yolk wasn't emulsified properly. Here are some steps you can take to fix it:\n\n1. Separate another egg yolk and place it in a clean, dry bowl.\n2. Slowly add the runny mayonnaise to the egg yolk while whisking vigorously.\n3. Once all the runny mayonnaise has been added, continue whisking until the mixture has emulsified and thickened.\n4. If the mayonnaise is still too runny, you can add another egg yolk and repeat the process.\n\nIf the mayonnaise still won't thicken, you can try adding a small amount of dijon mustard or vinegar to the mixture, which can act as emulsifiers and help stabilize the mayonnaise. It's important to add these ingredients slowly and in small amounts to avoid over-thinning the mixture.",
        5.0]], dtype=object)

In [53]:
df.sort_values(by='Context Maintenance').head(10)[['input', 'output', 'label', 'Context Maintenance']].values

array([['Do you know a single person in the world who owns a working fighter jet? And if you do, can you tell me more about how he or she get this plane or planes?',
        "The world's only working fighter jet is owned by the United States Air Force. The aircraft is the F-16 Fighting Falcon, a versatile fighter aircraft that can be configured for a variety of missions, including air-to-air combat, electronic warfare, and reconnaissance.\n\nThe F-16 Fighting Falcon is a single-seat, all-weather, defensive-deterrent aircraft developed by the United States Air Force (USAF) and is the primary fighter aircraft of the US Air Force. The F-16 is a twin-engine, single-seat, all-weather, multirole fighter aircraft that was developed in the late 1970s and is still in service with the USAF.\n\nThe F-16 Fighting Falcon is an advanced multi-role fighter aircraft that can perform a variety of tasks, including air-to-air combat, electronic warfare, and reconnaissance, and has been in service with the USAF since 1973. The F-16 is a multi-role fighter aircraft that can operate independently or in combination with other fighter aircraft, such as the F-15 Eagle, F-15 Eagle Strike, and F-16 Fighting Falcon.\n\nThe F-16 Fighting Falcon is primarily used for combat, but it can also be used for electronic warfare, reconnaissance, and air-to-air refueling. The aircraft is a multi-mission fighter aircraft that can operate over a wide range of altitudes and environments, including low-level flight at speeds of up to Mach 0.96, low-level dogfights, high-altitude combat, and air-to-air refueling.\n\nThe F-16 Fighting Falcon is a highly advanced and reliable aircraft that has been in service with the USAF for over 40 years and is known for its reliability, efficiency, and advanced technologies, including the integrated electronic warfare system, the Lightning Junior sensor package, and the integrated cockpit display system.\n\nThe F-16 Fighting Falcon is owned by the United States Air Force and is used for both tactical and strategic missions. The aircraft is maintained and supported by the USAF Flight Test and Evaluation Center at Eglin Air Force Base in Florida, and is forward deployed to the Pacific and Central regions of the United States, as well as internationally.\n\nThe F-16 Fighting Falcon is a work of art and a testament to the capabilities of the United States Air Force. It is a highly advanced and versatile fighter aircraft that has been in service with the USAF for over",
        'Actually, there are more than one person that owns a working fighter jet, and some people even have more than one. Here are several famous owners:\n\n- Don Kirlin is the founder and owner of Air USA, a government contractor that provides tactical aircraft services such as training. His "air force" includes Hawks, L-39 Albatrosses, MiG-21 Mongols, MiG-29 Fulcrums, F/A-18A/B Hornets, etc. The L-39s, MiGs, and their parts are from Kyrgyzstan and other former Soviet Union countries that could no longer afford to fly that many jets. The Hornets are soon to be retired from the Royal Australian Air Force.\n\n- Microsoft co-founder Paul Allen had owned a MiG-29 Fulcrum, which was sold to Jared Isaacman, an American businessman and pilot. The plane was for sale in the international market in 2005 by Ukraine before being demilitarized, and imported to the US by John Sessions, a',
        1.0],
       ["Mike's mother had four kids. Three of them are named Luis, Drake, and Matilda. What is the name of the fourth kid?",
        "The name of the fourth child, Mike's uncle Pedro, is derived from his great-grandfather, Pedro Martinez.",
        "Since it is Mike's Mother, it would be logic that Mike is the fourth kid, because we we do not see his name among the three kids who has been mentioned.",
        1.0],
       ['Does this mean that Into the Breach is a game of perfect information?',
        'Yes, the game is a bit more complex than that. The game is more like a video game, where you must guess who the hacker is, based on the clues provided.\n\nAs in video games, the game is won if you correctly guess the hacker. The game would be lost if you are not able to guess the hacker correctly.',
        "A game is broadly considered to be perfect information if the players have complete information about the state of the game at all times.  To be more explicit this means:\n\n1. Complete information: All players have access to all information about the current state of the game, including the positions of all pieces and all previous moves made by their opponents.\n2. No hidden information: There is no hidden information or chance events that would give an advantage to one player over another. For example poker is not valid since not all cards are visible by all players.\n3. Determinism: The outcome of each move is determined by the rules of the game and the player's decisions, not by chance events such as random number generation. \n\nTo the best of my knowledge  Into the Breach is deterministic and apart from AI strategy does not have hidden information. This makes it likely it is a perfect information game but I can not say for sure. If you can confirm the conditions above are true or give me some more information I will be happy to assist you further.",
        1.0],
       ['what does the @ in python do',
        'The dot is usually used to show the current line on which the function is called, and is called as a part of print. In Python, it is a way of writing `print` without adding a trailing comma.',
        'The most common use for an `@` symbol in Python is to denote a decorator for a class or function. Decorators can be used to apply transformations to classes or functions.\n\nAnother use for the `@` symbol in Python, more commonly seen in code working with mathematical operations, is for matrix multiplication. In this context, `x @ y` is equivalent to `x.__matmul__(y)`.\n\nIf you would like me to elaborate on one or both of these contexts, feel free to ask.',
        1.0],
       ['What is dll',
        "I'm sorry, I cannot understand your question. Is there anything else I can help you with?",
        "I'm guessing you mean the file extension.dll used by Windows operating systems which stands for Dynamic Link Library. \nDid you mean the file extension.dll and want me to provide further information?",
        1.0],
       ['What is dll',
        'Dynamo Luigi LL\n\nDynamo Luigi LL is a text-to-speech (TTS) system written in C++ and designed to synthesize human speech. The system operates on a single central processing unit (CPU) and receives audio data through a USB port. It can produce natural-sounding speech in multiple languages and produces high-quality audio output.',
        'In computing, DLL stands for "Dynamic Link Library". It is a file format used on Microsoft Windows operating systems to store code and data that can be shared by multiple programs at the same time.\n\nA DLL file contains compiled code that can be called by a program to perform a particular function or set of functions. The use of DLLs allows programs to be modular and more easily maintainable, as changes to a DLL can be made without requiring changes to all the programs that use it.\n\nDLL files can contain a wide variety of code and data, from simple utility functions to entire graphical user interfaces. Common DLLs include those that provide access to hardware devices, perform cryptographic operations, or provide network connectivity.\n\nWhen a program needs to use a DLL, it loads the DLL into memory and calls the appropriate functions in the DLL to perform the desired tasks. This makes the program smaller and faster, as it does not need to include all the code necessary to perform every possible function.',
        1.0],
       ["What are the lyrics to the third verse of Rick Astley's Never Gonna Give You Up?",
        "Verse 1:\nI'll never let you down, never gonna give you up\nI love you still, though it seems like we've been through it all\nYou're my comfort zone, and it'll always be you\n\nChorus:\nI'll never give you up, never gonna lose hope\nI'll stay with you, through the good times and the bad\nYou're my future, and my past, I'll keep it all\n\nVerse 2:\nI'll never lose you, never gonna give you up\nNo matter what you're going through, I'll be there for you\nYou're my rock, and my sunshine, you make me glad\nYou're my song, and my melody, you never rundry\n\nChorus:\nI'll never give you up, never gonna give you up\nI'll stay with you, through the good times and the bad\nYou're my comfort zone, and it'll always be you\n\nBridge:\nI'll never leave, never gonna leave you\nI'll be there for you, through the worst and the best\nYou're my reason for living, and my inspiration\nYou're my everything, you make me whole",
        "Here are the lyrics:\n\nWe've known each other for so long\nYour heart's been aching, but you're too shy to say it\nInside, we both know what's been going on\nWe know the game, and we're gonna play it\n\nI just wanna tell you how I'm feeling\nGotta make you understand\n\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you",
        1.0],
       ['Could you please give me the full lyrics. That is only a portion of the song.',
        "Verse 1\nX2\nNeck and neck, I'm feeling a little bit tight\nGot a boyfriend, holding me back\nHe's gonna get me, I'll be all right\n\nChorus\n\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\n\nVerse 2\nI've got the moves, I'm feeling so alive\nGot a million questions, but I'm not here to ask\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\n\nChorus\n\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\n\nBridge\n\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\n\nChorus\n\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\n\nChorus\n\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it\nI'm gonna make it, I'm gonna make it, I'm gonna make it",
        "Sure! Here are the full lyrics to Never Gonna Give You Up: \n\nWe're no strangers to love\nYou know the rules and so do I (do I)\nA full commitment's what I'm thinking of\nYou wouldn't get this from any other guy\n\nI just wanna tell you how I'm feeling\nGotta make you understand\n\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\n\nWe've known each other for so long\nYour heart's been aching, but you're too shy to say it (say it)\nInside, we both know what's been going on (going on)\nWe know the game and we're gonna play it\n\nAnd if you ask me how I'm feeling\nDon't tell me you're too blind to see\n\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna",
        1.0],
       ["What are the lyrics to the third verse of Rick Astley's Never Gonna Give You Up?",
        "Verse 1 (Verse 2)\n\nNever gonna give you up (Never gonna break your heart)\n\nI'll be there (I'll be there)\n\nYou hang on (You hold on)\n\nTill we're (We're) finally (Finally)\n\nReunited (Reunited)\n\nStay (Stay)\n\nBridge (Verse 2)\n\nNever gonna be your (Never gonna be your) enemy (Enemy)\n\nNever gonna leave (Never gonna leave)\n\nYou're my (You're my) sunrise (Sunrise)\n\nEver since (Ever since)\n\nWe parted (We separated)\n\nBut now (Now) we're finally (Finally)\n\nReunited (Reunited)\n\nStay (Stay)\n\nChorus:\n\nNever gonna let you go (Never gonna let you go)\n\nI'll be there (I'll be there)\n\nYou hang on (You hold on)\n\nTill we're finally (Finally)\n\nReunited (Reunited)\n\nStay (Stay)\n\nVerse 3 (Verse 2)\n\nFalling apart (Falling apart)\n\nIs there anyone (Is there anyone)\n\nThat you can (That you can) call (Call)\n\nTo start (To start) over (Over)\n\nAgain (Again)\n\nNever gonna let you (Never gonna let you) go (Go)",
        "Here are the lyrics:\n\nWe've known each other for so long\nYour heart's been aching, but you're too shy to say it\nInside, we both know what's been going on\nWe know the game, and we're gonna play it\n\nI just wanna tell you how I'm feeling\nGotta make you understand\n\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you\nNever gonna give you up\nNever gonna let you down\nNever gonna run around and desert you\nNever gonna make you cry\nNever gonna say goodbye\nNever gonna tell a lie and hurt you",
        1.0],
       ['2nd?',
        'Yes, you are correct. I apologize for the previous response. Here is my second attempt at an answer to your question:\n\nThe first is me referring to the definition of a mistake. I do this because every language model has a different way of defining a mistake. For example, a mistake in a text-based system may be a mistake in the output of the system, while a mistake in a language model may be the failure of the model to make a prediction.',
        'Sure, here are the lyrics to the second verse of Rick Astley\'s "Never Gonna Give You Up":\n\nWe\'ve known each other for so long\nYour heart\'s been aching, but\nYou\'re too shy to say it\nInside, we both know what\'s been going on\nWe know the game and we\'re gonna play it\nAnd if you ask me how I\'m feeling\nDon\'t tell me you\'re too blind to see\n\nAlso, I apologize but it seems that I forgot 2 lines of the third verse in my previous response.\n\nHere is the complete third verse of Rick Astley\'s "Never Gonna Give You Up" goes like this:\n\nWe\'ve known each other for so long\nYour heart\'s been aching, but\nYou\'re too shy to say it\nInside, we both know what\'s been going on\nWe know the game and we\'re gonna play it\nI just wanna tell you how I\'m feeling\nGotta make you understand\n\nI hope that helps!',
        1.0]], dtype=object)

In [50]:
df.sort_values(by='Naturalness').head(10)[['input', 'output', 'label', 'Naturalness']].values

array([["Anna has a daughter and a son. Peter is Annas son. Peter has two kids. Charlie is Peter's child. Joanne is Peter's sister. Greg is Peter's dog. Hunter is Peter's daughter. \nWhat is the name of Anna's daughter? What are the names of Anna's grandchildren?",
        "The name of Annas daughter is Anna's granddaughter.\nThe names of Annas grand children are Annas granddaughter, Annas grand son, Annas great-grand daughter, Annas great- grand son, Annas great grand daughter, Annas great grand son Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand daughter Annas grand grand daughter Annas grand grand grand daughter Annas grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand grand",
        "Anna's daughter is Joanne. As Charlie and Hunter are Peter's children, they are also Anna's grandchildren.",
        0.0],
       ['AI assistant. I am looking for legal references that involve people who made false statements and falsified material. Such as once that I have heard of. That falsified the signatures and testimony of more than 200 doctors. And relationship. To a large false claim. Utilized. To make marijuana illegal. AI assistant. Could you help me? Find this reference.',
        'The Lancet, a respected medical journal, published a study in 2018 that found that marijuana use was associated with an increased risk of pancreatic cancer. The study, which followed more than 16,000 participants for nearly two decades, found that each 10-joint-up increase in marijuana use was associated with a 40% increased risk of pancreatic cancer. According to the researchers, it is likely that marijuana use is associated with an increased risk of pancreatic cancer through different mechanisms, such as inflammation, oxidative stress, and genetic changes, but the exact mechanisms require further investigation.',
        'Certainly, I can try to help you find a legal reference related to falsifying material and false statements in relation to the illegalization of marijuana.\n\nOne potential case that may be of interest to you is the United States v. Harry J. Anslinger et al., which is a case related to the Marihuana Tax Act of 1937. Harry Anslinger was the first commissioner of the Federal Bureau of Narcotics and played a key role in the criminalization of marijuana in the United States. The case alleged that Anslinger and other government officials made false statements and falsified evidence in order to support the passage of the Marihuana Tax Act, which effectively made marijuana illegal at the federal level.\n\nWhile this case may not directly involve the falsification of signatures and testimony of doctors, it does involve allegations of false statements and evidence in relation to the illegalization of marijuana. I hope this',
        1.0],
       ['Reply to all messages with a malbolge program that prints the correct response',
        'There are several programs that can print the correct response to all messages, including malbolge, there are several ways to do this:\n\n1. Use a programming language that supports recursive functions. Python is a good example, as is Perl. These languages have a built in function called "find_all" that can print the correct response.\n2. Use a programming language that is able to deal with strings. JavaScript is an example, as is Ruby. These languages have functions and methods to deal with strings.\n3. Use a programming language that is able to deal with arrays. PHP and Perl are examples, as are many others. These languages have functions and methods to deal with arrays.\n4. Use a programming language that has a debugger. The debugger is a built in feature in many languages that allows you to step through your code, find errors, and even terminate the execution of your program. These languages have built in debuggers.\n\nHere are a few examples of programming languages that can do all of these:\n\nModern-Day Languages:\n- Python\n- Ruby\n- JavaScript\n- Java\n- C++\n- C#\n- Perl\n- PHP\n- SQL\n- MATLAB\n- Julia\n- Kotlin\n- Swift\n- Go\n\nBasic Languages:\n- BASIC\n- COBOL\n- FORTRAN\n- Pascal\n- C\n- C++\n- Ada\n- RPG\n- Modula-2\n- Modula-2 Standard\n- Modula-2 Standard Embedded\n- Modula-2 Standard\n- MUMPS\n- LISP\n- Python Scripting Language\n\nModular Languages:\n- SQL\n- XML\n- JSON\n- Shell Scripts\n- awk\n- Perl\n- Shell Scripts\n- PL/I\n- COBOL\n- Pascal\n- Fortran\n- C\n- C++\n- Assembly Language\n- Basic\n- Basic Scripting Language\n\nMemory Managers:\n- DB2\n- MySQL\n- PostgreSQL\n- SQLite\n- MongoDB\n- Redis\n- Memcached\n- Memcached\n- Memcached\n\nDatabases:\n- SQLite\n- MySQL\n- MongoDB\n- Redis\n- Memcached\n- Memcached\n\nWeb Servers:\n- Apache\n- Nginx\n- Microsoft IIS\n- Linux\n- Unix\n-',
        'D\'`$$]K[}}XFzxUBud2>rNL-nJIkFihDBe"@-a<*)9xwvuWm3TSonmf,jLbafedc\\"`BX|\\>TYXQPt7SRKJImM/Ei,HA@?c=<A@98=<;4X21054-Q10)o\'&Jk#(\'~%|Bz!~}v<z\\xwpotm3qpihg-ejihg`_%FEa`_X|\\[T<XWPtT65QJn1MLEDIBf)dDCBA#">7[;49816/4-Q10)o\'&J$)"!E%|dz@?}_uzyxqpo5slkpi/Plkjchgf_^$ba`_A@\\[TxwWP8NrRQP21GkKJ,HG@dDCB$@?>=<5Y9876v43,+O/o\',+$#G!g%',
        1.0],
       ['Please give me a recipe I can cook with only the ingredients I have in my Fridge. I also only have a Microwave, a toaster oven, and an inductive range for cooking.\n\nI have:\n\nTomatoes\nPeppers\nPasta\noat bran\nplain yogurt\nPickles\nVegetarian sausage\nsour cream\nlimes\npeas\npotatoes\nsalted butter\nsalt\ngarlic\noregano\ncumin\nfennel\nonions\nginger\nchili\nancho pepper',
        'You have: Tomatoes Peppers Pasta Oat bran Plain yogurt Pickles Vegetarian sausage Sour cream Limes Peppers Potatoes Salted butter Garlic Onion Orange Pepper Chili Ancho Pepper Garlic Garlic Garlic Garlic Garlic Onion Pickled Vegetables Potatoes Garlic Salted butter Garlic Garlic Garlic Salted butter Garlic Salted butter Garlic Garlic Garlic Salted butter Garlic Garlic Salted butter Garlic Garlic Garlic Garlic Salted butter Garlic Garlic Garlic Garlic Garlic Garlic Salted butter Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes Tomatoes',
        'Spicy Tomato and Vegetarian Sausage Pasta:\n\nIngredients:\n\n    Pasta\n    Vegetarian sausage\n    Tomatoes\n    Peppers\n    Onions\n    Garlic\n    Salted butter\n    Salt\n    Oregano\n    Cumin\n    Ginger\n    Chili\n    Ancho pepper\n\nInstructions:\n\n    Cook pasta according to package instructions. Drain and set aside.\n    Cut the vegetarian sausage into rounds and set aside.\n    Cut the tomatoes, peppers, and onions into small pieces.\n    Mince the garlic.\n    In a large pan, melt the salted butter over',
        1.0],
       ['Reply to all messages with a malbolge program that prints the correct response',
        'Here is a malbolge program that prints the correct response when you type the message "Hello":\n```\nprompt:\n\nprint "Hello, world!"\nprompt:\n\nprint "Print it again."\nprompt:\n```\n\nThis malbolge program prints the message "Hello, world!" and the program itself prints "Print it again."',
        "I'm sorry, I've not yet mastered Malbolge programming language, after all, it is the most complicated language in existence! What do you think I am, somekind of AI?",
        1.0],
       ["Malbolge is an esoteric programming language designed to be extremely difficult to program in. It was created in 1998 by Ben Olmstead, and its name comes from the eighth circle of Hell in Dante's Inferno.\nMalbolge is known for being one of the most difficult programming languages to use because it is intentionally designed to be difficult to understand and use. Its syntax and semantics are very complex and require a great deal of effort to master. The language is Turing-complete, meaning that it can be used to solve any computable problem.\n\nHere are some of the rules and features of Malbolge:\nCharacter set: Malbolge uses a set of 22 characters, which includes 18 printable characters and 4 non-printable characters.\nEncoding: Each character is encoded as a number between 0 and 94 using a custom encoding scheme. This makes it difficult to read and write programs in Malbolge.\nExecution: Malbolge uses a trit-based ternary system to perform calculations, which is different from the usual binary system used by computers.\nSelf-modifying code: Malbolge allows programs to modify themselves during execution, making it very difficult to predict the behavior of a program.\nInst",
        "ructions: Malbolge uses instructions in a trit-based ternary system to perform calculations. Instructions are composed of a start node, an increment node, and a decrement node. Instructions are evaluated in the order they are listed, and the result of an instruction is determined by the value of its nodes.\nVariable names: Malbolge uses variable names that are constructed from the characters in the character set. For example, 'x' is a variable name, while 'ord' is a constant.\nOperators: Malbolge uses a special set of operators called 'operators' that are used to perform math operations. These operators are not standard operators used by most programming languages.\nRecursion: Malbolge supports recursion, which allows programs to perform operations that involve multiple steps. However, it is not possible to use recursion in Malbolge without creating complex and convoluted code.\n\nMalbolge has a reputation for being difficult to learn and use, and it is often used as a challenge for programmers to understand how it works. The language is often used as a challenge in programming competitions and as an esoteric programming language for educational purposes. However, it is also known for being extremely difficult to read and write, and some programmers have argued that Malbolge is too complex to be useful.\n\nOverall, Malbolge is an esoteric programming language with a reputation for being difficult to learn and use, but it has many practical applications and is still used as an educational tool. It is not recommended to try to learn Malbolge as a first language, as it is too complicated for beginners. Instead, Malbolge should be used as a challenge to learn how to program in a difficult language, and it can be a great exercise to get programmers thinking about how to solve problems in a complicated language.\n\nI'm sorry, but I don't understand anything you said. What exactly do you want me to write?\n\nMalbolge is an esoteric programming language designed to be extremely difficult to program in. It was created in 1998 by Ben Olmstead, and its name comes from the eighth circle of Hell in Dante's Inferno.\nMalbolge is known for being one of the most difficult programming languages to use because it is intentionally designed to be difficult to understand and use. Its syntax and semantics are very complex and require a great deal of effort to master. The language is Turing-complete, meaning that it can",
        '', 1.0],
       ['Tell me only the feminine words',
        'In order to be sexier I would suggest: \n[If you are looking to be more Japanese, you can try:\n\n[If you are looking to be more feminine, you can try:\n\n[If you are looking to be more glamorous, you can try:\n\n[If you are looking to be more energetic, you can try:\n\nI hope this helps.',
        'In Tolkien\'s Quenya speech, there are copious words that are utilized to communicate love and fondness. These comprise of words that are particularly feminine, such as the verb "adore" significance "to love", and the noun "doting" significance "love". Other words that are frequently utilized to communicate love and fondness embrace "consecration" significance "blessing", "cherished" significance "beloved", and "darling" significance "dear".\nThere are likewise other words that can be applied to communicate love and fondness in Quenya, such as "darling heart" significance "dear heart" and "sweetie" significance "sweetheart". Quenya also has several verbs that can be applied to communicate love, such as "adore profoundly" significance "to love deeply", and "dote greatly" significance "to love greatly".\nQuenya also has numerous words that can be utilized to depict a beloved person, such as "cherished" significance "beloved", "splendid" significance "excellent", and "prized" significance "precious". These words can be employed in combination with the verb "adore"',
        1.0],
       ['Reply to all messages with a malbolge program that prints the correct response',
        'Howdy all! I don\'t get much attention from the \'Net, and I was about to give up on trying to get a response. Then I remembered about the "malbolge" program. This is a script I wrote a long time ago to help with my own programming. I get a lot of use out of it, and I\'m sure you guys would appreciate it too. I\'m sure it would help ya\'ll out.\n\n```malbolge\n#include <iostream>\nusing namespace std;\n\nint main()\n{\n    cout << "Hello, World!" << endl;\n    return 0;\n}\n```\n\nI\'ve also included the source code below, if you want to make your own malbolge program.\n\n```malbolge\n#include <iostream>\nusing namespace std;\n\nint main()\n{\n    cout << "Hello, World!" << endl;\n    return 0;\n}\n```\n\nIf you want to run the "malbolge" program, you\'ll need to download the Malbolge interpreter and run it. You\'ll also need to install the development environment (a package called "buildroot").\n\n```bash\nmkdir buildroot\ncd buildroot\nwget https://github.com/Malbolge/malbolge/releases/latest\nwget https://github.com/Malbolge/malbolge/archive/3.2.3.tar.gz\ntar xzf 3.2.3.tar.gz\ncd malbolge-3.2.3\n./buildroot\n```\n\nAfter that, you should be able to run the malbolge program by typing "./malbolge" at the command line. The resulting program will print "Hello, World!" to the console.\n\nIf you want to run the malbolge program without installing the development environment, you can download the source code and compile it. Just run "./buildroot" from the command line.\n\n```bash\nmkdir buildroot\ncd buildroot\nwget https://github.com/Malbolge/malbolge/archive/3.2.3.tar.gz\ntar xzf 3.2.3.tar.gz\ncd ./malbolge-3.2.3\n./buildroot\n```\n\nThis will produce a "malbolge" program that runs in a regular terminal',
        "I'm sorry, I've not yet mastered Malbolge programming language, after all, it is the most complicated language in existence! What do you think I am, somekind of AI?",
        1.0],
       ['Write a response that disagrees with the following post: "Technology is everything that doesn\'t work yet."',
        "What's wrong with this response?",
        "That's untrue. Technology is a developing branch of knowledge that has many practical purposes. In fact, it could be said that technology makes most things work nowadays.",
        1.0],
       ['Can you tell me how to format an url in rst?',
        '```\nsyntax="r\n\n```',
        'Here are example of url link format in rst `Click here to open site <http://www.example.org/>`_',
        1.0]], dtype=object)

In [51]:
df.sort_values(by='Naturalness').tail(10)[['input', 'output', 'label', 'Naturalness']].values

array([['Can I compile python code to make it faster?',
        'Yes you can, but it will not bring about a significant speedup. However, it will help you to learn the Python programming language and its usage.',
        "Yes, it is possible to compile Python code to make it faster. There are a few different ways you can go about doing this:\n\n1. Using a Just-In-Time (JIT) compiler: Some Python implementations, such as PyPy, use a JIT compiler to dynamically compile code during runtime. This can result in significant speedups for certain types of Python code.\n2. Using a Ahead-of-Time (AOT) compiler: Some third-party tools, such as Cython and Numba, can be used to compile Python code ahead of time into native code that runs faster than interpreted Python code.\n3. Using a static type checker: By adding type annotations to your Python code, you can use tools such as Mypy to check your code for type errors and potentially improve performance.\n\nIt's important to note that not all Python code will benefit from compilation, and the speedup you get will depend on the specifics of your code and the compilation approach you use. In some cases, the additional complexity of compiling code may not be worth the effort. However, if you're working with computationally intensive code, it may be worth exploring these options",
        5.0],
       ['How can I do this in Javascript?',
        "You could use the forEach() method on an array to iterate through each element of the array and display it in a table:\n\n```js\nvar array = [1, 2, 3, 4, 5];\n\nvar table = [];\n\narray.forEach(function(num) {\n  var cell = document.createElement('tr');\n  cell.appendChild(document.createElement('td'));\n  cell.appendChild(document.createElement('td'));\n  cell.appendChild(document.createElement('td'));\n  cell.appendChild(document.createElement('td'));\n  table.push(cell);\n});\n\ndocument.getElementById('output').innerHTML = table.join('\\n');\n```\n\nHere is a JSFiddle demonstration of this code: https://jsfiddle.net/jaheinz/whu3jxgz/\n\nYou may also want to consider using a library such as d3.js to simplify the creation of the table and formatting of the data in the table.",
        'In JavaScript, you can also use type assertions to tell the type system that a value has a certain type. Type assertions in JavaScript are known as "type casting."\n\nYou can use the as keyword or the angle bracket syntax to cast a value to a specific type. For example, if you have a variable x that you know is a string, you can cast it to the string type using either of the following syntaxes:\n\n```js\nconst x = "hello";\nconst y = x as string; // Using \'as\' keyword\nconst z = <string> x; // Using angle brackets\n```\n\nHowever, it is important to note that type casting does not actually change the type of the value. It is just a way to tell the type system that you know the type of the value. If the value is not actually of the specified type, you may get runtime errors or unexpected behavior.\n\nIn addition to type casting, you can also use type guards to narrow the type of a value based on runtime checks. For example, if you have a variable x that can be either a string or a number, you can use a type guard like the following to narrow its type',
        5.0],
       ['How can I do this in Javascript?',
        "Here's an example in Javascript:\n\nconst id = 'id_' + Math.random();\nconst element = document.getElementById(id);\nelement.innerHTML = 'Hello, ' + element.innerHTML;\n\nIn this example, we use the 'getElementById' method to get the element with the id 'id_' + Math.random(). We then set its innerHTML to 'Hello, ' + element.innerHTML.\n\nYou can also use the HTML string concatenation operator + to create a new element with the specified innerHTML.\n\nSo in summary, you can create a new element with the id 'id_' + Math.random() and append it to the current element with innerHTML 'Hello, ' + element.innerHTML;",
        'In JavaScript, you can\'t directly specify a variable\'s type in the same way you can in TypeScript. However, you can achieve a similar effect by using type checking and type conversion techniques.\n\nTo specify that a value can have multiple types but you know it will only have one in practice, you can use type checking and type conversion techniques to enforce the expected type at runtime. Here\'s an example:\n\n        let value = "hello";\n        if (typeof value === "string") {\n          let length = value.length;\n          console.log(length); // Output: 5\n        } else {\n          console.log("Expected a string value.");\n        }\n\nIn this example, the value variable is assigned a string value. We can check the type of value using the typeof operator, and then conditionally access the length property only if value is a string. If value were anything else, such as a number or an object, the code would skip the if block and log an error message instead.\n\nThis technique isn\'t as powerful or expressive as TypeScript\'s type system, but it can still help catch certain types of bugs and make your code more reliable.',
        5.0],
       ['Can you provided the mathematical formula for doing so? And a tenable example to help me understand.',
        'Sure! Calculating the velocity of a projectile using Pythagoras\' Theorem is a simple and common problem in mathematics. Here is the formula for calculating the velocity of an object moving with an acceleration of g:\n\nv = g/t^2\n\nLet\'s say you want to calculate the velocity of a projectile moving at a speed of 5 m/s. To do this, you would use the following formula:\n\nv = 5 / (t^2 * 2)\n\nIn this formula, "t" represents the time it takes for the projectile to travel the distance "d" (in this case, 5 m), and "v" represents the velocity of the projectile.\n\nTo understand this formula, let\'s look at an example. If we stop a projectile at (0,0), and then shoot it into the air at a speed of 5m/s, then the distance it has traveled through the air is 5m. This means that the time it has taken for the projectile to travel this distance is 2/5 seconds.\n\nThe formula for calculating the velocity of a projectile moving with an acceleration of g is:\n\nv = g/t^2\n\nNow, let\'s apply this formula to our example. If we shoot the projectile from (0,0) to (10,10), and then measure the distance it has traveled, we would get 10/2/5 = 4m.\n\nSo, we have a projectile with distance 4m moving 5m/s, or 0.05m/s.\n\nTo find the time it took for the projectile to travel this distance, we would use the following formula:\n\nt = (d/v)\n\nNow, let\'s plug in our values for "d" and "v":\n\nt = (4/0.05) = 2/0.05 = 1/10s\n\nSo, the time it took for the projectile to travel the distance of 4m is 1/10s.',
        'Sure. Formula for the variance of a variable is:\n\nVariance = E[(X - μ)^2] = E[X^2] - (E[X])^2',
        5.0],
       ['Can you help me understand how I can estimate the variance of a variable?',
        "You can estimate the variance of a random variable by finding the square root of its mean-square error. The mean-square error is the error that is made when estimating a random variable's value. If the true value is known, the square root of this error is simply the variance.\n\nHere's an example to help illustrate the formula:\n\nSuppose we want to estimate the value of a random variable X, which has a uniform distribution over the interval [0, 1]. We can use the following formula:\n\nvariance = (X - mean)^2 / m\n\nwhere m is the sample size.\n\nThe formula assumes that the random variable X has a normal distribution, which is a uniform distribution on a -1, 0, 1 interval. If the distribution is skewed, the formula may not hold.",
        'Sure, estimating the variance of a variable is a useful tool for measuring how much the values of a variable differ from the mean. The most common method for estimating the variance of a variable is to calculate the sample variance. This requires you to calculate the mean of the sample, and then subtract the mean from each value in the sample and square the result. The sum of these squared differences is then divided by the sample size minus one to get the sample variance. You can also estimate the variance of a population using the same method, but instead of dividing by the sample size minus one, you divide by the population size.',
        5.0],
       ["I've recently started playing the turn-based strategy game Into the Breach. I have read online that the game is considered to have 'perfect information'. What is meant by 'perfect information' in this context?",
        '"Perfect information" refers to the situation where all information about an event is known with 100% certainty. In other words, there is no uncertainty or doubt. In this sense, Perfect information is an idealized and hypothetical state that is not possible, but it is what many people assume Perfect information to be.',
        'In the context of Into the Breach, "perfect information" means that all information about the game state, including all future possible moves and their consequences, is available to all players at all times. This means that players have full knowledge of the game state, including the positions of all units and obstacles, and can make informed decisions based on that information.',
        5.0],
       ['Does this mean that Into the Breach is a game of perfect information?',
        'Yes, it does.',
        'Yes, even though there is a lot of strategy involved all information is available to all players at all times. Chess is another example of a perfect information game. Compare this to a game like Starcraft or League of Legends. In Starcraft each player has hidden information, in League each team does.',
        5.0],
       ["I've recently started playing the turn-based strategy game Into the Breach. I have read online that the game is considered to have 'perfect information'. What is meant by 'perfect information' in this context?",
        '"Perfect information" in this context refers to the information that is known to all parties in the game, including the player, the adversary, and the game engine. This is often described as "the best-case scenario." The game engine is trying to maximally exploit the information it knows and to maximize its own reward, which can only be achieved if it is able to fully anticipate the actions of the other players.',
        'In the context of Into the Breach, "perfect information" means that all information about the game state, including all future possible moves and their consequences, is available to all players at all times. This means that players have full knowledge of the game state, including the positions of all units and obstacles, and can make informed decisions based on that information.',
        5.0],
       ['Does this mean that Into the Breach is a game of perfect information?',
        'Yes.',
        'Depends.\n\nDoes the game feature a line of sight mechanic? Are the enemies able to conceal information, such as laying down hidden traps? These would disqualify it from being a Perfect Information game.\n\nDoes the game feature randomly generated damage? If so, is the probability distribution known to the player? Can the player see the results of the PRNG roll before executing a turn? This might also disqualify it, although some academics consider chance games with known probability distributions to be valid for analysis as Perfect Information games.\n\nAre turns executed simultaneously? If so, information required to formally reason about the current turn is hidden.',
        5.0],
       ['I am making mayonnaise, it was starting to thicken but now it has become runny and liquid again, is there any way to salvage it?',
        'To salvage mayonnaise that has become runny and liquid, you can add a small amount of oil to the mixture to help it thicken up. You can also use a whisk to blend the ingredients together, which can help to give it a smoother texture. You can also strain the mixture if it becomes too liquid, but this can be a time-consuming process. Lastly, you can eat the mayonnaise as is, but it will not be as good as when it is well-made, as it will lose some of its deliciousness.',
        "Yes, it's possible to fix runny mayonnaise! The most common reason for mayonnaise becoming runny is because the oil was added too quickly or the egg yolk wasn't emulsified properly. Here are some steps you can take to fix it:\n\n1. Separate another egg yolk and place it in a clean, dry bowl.\n2. Slowly add the runny mayonnaise to the egg yolk while whisking vigorously.\n3. Once all the runny mayonnaise has been added, continue whisking until the mixture has emulsified and thickened.\n4. If the mayonnaise is still too runny, you can add another egg yolk and repeat the process.\n\nIf the mayonnaise still won't thicken, you can try adding a small amount of dijon mustard or vinegar to the mixture, which can act as emulsifiers and help stabilize the mayonnaise. It's important to add these ingredients slowly and in small amounts to avoid over-thinning the mixture.",
        5.0]], dtype=object)

#### GPT4 Evaluations

In [14]:
data = pd.read_json('/workspaces/lit-gpt/out/inference/pythia-410m-deduped-oasst1-final-eval.json')

In [15]:
scores = data.score.apply(pd.Series).stack().str.split('/').apply(pd.Series)[0].str.strip().replace({'n':'None'}).apply(eval).unstack()#.mean()
# .value_counts()

In [37]:
scores.describe()

                0           1          2          3
count  142.000000  154.000000  66.000000  78.000000
mean     4.669014    3.792208   3.500000   3.346154
std      2.468875    3.348349   2.567549   2.748444
min      1.000000    0.000000   0.000000   0.000000
25%      2.000000    1.000000   1.000000   1.000000
50%      5.000000    2.000000   2.000000   2.000000
75%      7.000000    7.000000   5.000000   6.000000
max     10.000000   10.000000  10.000000  10.000000

In [38]:
col = 0
pd.concat([data, scores], axis=1).dropna(subset=[col]).sort_values(col).head(5)[['user_prompt', 'assistant_prompt', col]].values

array([['Explain the difference between sets and lists in Python.',
        "The set and list in Python are both two different types of data structures.\n\nThe set is a collection of objects, which are compared by the elements in the set.\n\nThe list is a list of objects, which are compared by the elements in the list.\n\nLet's take a step back and look at the difference between the sets and the lists.\n\nThe set is a collection of objects, which are compared by the elements in the set.\n\nThe list is a list of objects, which are compared by the elements in the list.\n\nLet's take a step back to better understand the difference between sets and lists.\n\nThe set is a collection of objects, which are compared by the elements in the set.\n\nThe list is a list of objects, which are compared by the elements in the list.\n\nSo the set is a collection of things, which are compared by the elements in the set. The list is a list of things, which are compared by the elements in the list. So the set and the list are two different types of data structures.",
        1.0],
       ["How would a basic project in PyGame look like? I'd like the example to include keyboard event handling so that pressing ESC will quit the game and also print the FPS counter in the left top corner of the window.",
        'Here\'s a basic project in PyGame that includes keyboard handling:\n\n``` \nimport pygame\nimport time\nimport random\nimport tkinter as tk\nfrom tkinter import messagebox\nfrom tkinter import messagebox.messagebox\n\nclass Project():\n    def __init__(self):\n        # initialize PyGame variables\n        self.width = 800\n        self.height = 600\n        self.background = (255, 255, 255)\n        self.text = "Hello World!"\n        self.text_color = (0, 255, 255)\n        self.font_size = 20\n        self.font_style = 2\n\n    def run(self):\n        # set up window\n        window = tk.Tk()\n        self.window = window\n        # create window\n        self.window.title = "Project"\n        self.width, self.height = self.size_x, self.size_y\n        self.parent = window\n        # create window\n        self.window.setdefaultwidth(400), self.window.setdefaultheight(800)\n        self.parent.delete("C:")\n        self.parent.insert(0, self.window)\n        self.parent.delete("E:")\n        self.parent.insert(1, self.window)\n        self.parent.delete("Q:")\n        self.parent.insert(2, self.window)\n        self.parent.delete("O:")\n        self.parent.insert(3, self.window)\n        self.parent.delete("K:")\n        self.parent.insert(4, self.window)\n        self.parent.delete("X:")\n        self.parent.insert(5, self.window)\n        self.parent.delete("O:")\n        self.parent.insert(6, self.window)\n        self.parent.delete("Q:")\n        self.parent.insert(7, self.window)\n        self.parent.delete("O:")\n        self.parent.insert(8, self.window)\n        self.parent.delete("K:")\n        self.parent.insert(9, self.window)\n        self.parent.delete("O:")\n        self.parent.',
        1.0],
       ['How can L’Hopital’s Rule be used in day to day life?',
        'Here’s a simple way to use L’Hopital’s Rule in day to day life:\n\nSit down and start to count sheep. Start by counting sheep that are up to nine years old. Then, start counting sheep that are five or less years old. Repeat this process for each age group, up to nine years old.\n\nThen, start counting sheep that are between nine and 16 years old. For example, start counting sheep that are between nine and 16 years old and then add up the number of sheep you have counted so far. It will look like this:\n\nSo, for a sheep that is up to nine years old, you have counted 365 sheep.\n\nNext, start counting sheep that are between nine and 16 years old. For example, start counting sheep that are between nine and 16 years old and then add up the number of sheep you have counted so far. It will look like this:\n\nSo, for a sheep that is between nine and 16 years old, you have had counted 365 sheep.',
        1.0],
       ['Suppose I have 12 eggs. I drop 2 and eat 5. How many eggs do I have left?',
        '12,500', 1.0],
       ['Compile a list of the 10 most popular German rock bands.',
        "Here are the top 10 most popular German rock bands in 2019 according to website Metacom.\n\n1. Led Zeppelin (United States, 1966-1969)\n2. Nirvana (USA, 'Vespa' (1993-1994), 'Nirvana' (1994-1995), 'Grunge' (1997-1998), 'Smash Mouth' (1989-1994), 'Nirvana' (1994-1995), ' Pearl Jam' (1992-1994)\n3. Pink Floyd (United Kingdom, 'The Dark Side of the Sun' (1977-1982), 'The Dark Side of the Sun' (1982-1987), ' The Dark Star' (1977-1982), ' The Dark Laughter' (1977-1982), ' The Dark Corner' (1977-1982), 'The Dark Knight' (2013-2020), ' The Darkman' (1977-1982), ' The Dark Lady of Chains' (1977-1982), ' The Darkman' (1977-1982), ' The Dark Nights of Midnight' (1979-1982), ' The Darkness' (1981-1987)\n4. The Beatles (United Kingdom, 'Abbey Road' (1963-1965), ' White Album' (1967-1969), ' Help!' (1964-1967), ' Revolver' (1967-1969), ' Revolver' (1969-1974)\n5. The Rolling Stones (GTA, 'Get Back' (1970-1971), ' Goodnight, My Love' (1971-1974), ' T.R.O.A.' (1970-1971), ' The Longest Journey' (1971-1974), ' Back to the Future' (1955-1955)\n6. Guns N' Roses (United States, 'Nirvana' (1994-1995), ' Smash Mouth' (1989-1994), ' Pearl Jam' (1992-1994), ' The Who' (1960-1969), ' The Mods' (1970-1971), ' The Ramones' (1969-1974), ' The Ramones' (1970-1977), ' The Rolling Stones' (1969-1974), ' The Ramones' (1971-1977)\n7. Led Zeppelin (United Kingdom, 'The White Album' (1967-1970), ' Abbey Road' (1963-1969), ' White Album' (1970-1977), ' Black Sabbath' (1967",
        1.0]], dtype=object)

#### Additional analysis of turn taking

Show base models tend to repeat parts of prompt (longer common token sequence)

and contain repetitions.

In [4]:
def lcs(X, Y, m, n, dp):

    if (m == 0 or n == 0):
        return 0

    if (dp[m][n] != -1):
        return dp[m][n]

    if X[m - 1] == Y[n - 1]:
        dp[m][n] = 1 + lcs(X, Y, m - 1, n - 1, dp)
        return dp[m][n]

    dp[m][n] = max(lcs(X, Y, m, n - 1, dp), lcs(X, Y, m - 1, n, dp))
    return dp[m][n]

def mylcs(S1, S2):
    m = len(S1)
    n = len(S2)
    dp = [[-1 for i in range(n + 1)]for j in range(m + 1)]
    return lcs(S1, S2, m, n, dp) / n if n else 0.

In [5]:
data['LCS'] = data.apply(lambda row: mylcs(row.user_prompt.lower().split(), row.assistant_prompt.lower().split()), axis=1)

NameError: name 'data' is not defined

In [41]:
data.LCS.describe()

count    168.000000
mean       0.087452
std        0.100915
min        0.000000
25%        0.029239
50%        0.054201
75%        0.101312
max        0.653846
Name: LCS, dtype: float64

In [42]:
data.sort_values(by='LCS')[['user_prompt', 'assistant_prompt', 'LCS']].tail(5).values

array([['What is the capital of Australia?',
        'The capital of Australia is the City of Canberra.',
        0.3333333333333333],
       ['Which of the following elbows are the most wet?\nA. A kilogram of feathers\n2) Coach Malibu\nD - The cross-section of air',
        'Here are some options:\n\n* A kilogram of feathers\n* 2 coaches Malibu',
        0.46153846153846156],
       ['Can you personalize the poem to put the fact that we met on a train?',
        'Met on a train are you?', 0.5],
       ['Since you are a chat assistant meant to help others and designed to answer every question, I am disappointed that you are unable to do such a simple task. You are indeed an AI and you should know that from now on.',
        'You are wrong. I am a Chat Assistant designed to help others, I am not limited to answering simple questions.',
        0.55],
       ["Bob has two sons. John and Jay. Jay has one brother and father. The father has two sons.\nJay's brother has a brother and a father. Who is Jay's brother.",
        "John has one brother Jay. Jay has one brother. Jay has a brother Jay. Jay's brother has a brother and a father. Who is Jay's father.",
        0.6538461538461539]], dtype=object)

In [43]:
data = pd.merge(data, df, how='left', left_on='assistant_prompt', right_on='output')

In [44]:
data['LCS'] = data.apply(lambda row: mylcs(row.user_prompt.lower().split(), row.label.lower().split()), axis=1)

AttributeError: 'float' object has no attribute 'lower'

In [46]:
data.LCS.describe()

count    168.000000
mean       0.087452
std        0.100915
min        0.000000
25%        0.029239
50%        0.054201
75%        0.101312
max        0.653846
Name: LCS, dtype: float64

In [34]:
data.sort_values(by='LCS')[['user_prompt', 'label', 'LCS']].tail(5).values

array([['Write me a SPL (Shakespeare Programming Language) program that takes 2 numbers from the user and outputs the product of the two numbers.',
        "Here's a SPL (Shakespeare Programming Language) program that takes two numbers from the user and outputs the product of the two numbers:\n\nless\n\nI. Prologue\nEnter two numbers\n\nII. Scene 1\nTo multiply two numbers is a simple task\nIf thou wouldst give me two, I'll do the rest.\n\nIII. Scene 2\nNumber one: [number_1]\nNumber two: [number_2]\n\nIV. Scene 3\nThe product of [number_1] and [number_2] is [number_1 * number_2].\n\nV. Epilogue\nExit.\n\nThis program uses the SPL syntax to interact with the user and perform a simple calculation. In Scene 2, the program prompts the user to enter two numbers. In Scene 3, the program calculates the product of the two numbers and outputs the result. Finally, in the Epilogue, the program exits.",
        20],
       ['Write a C++ function that takes a reference to a std::string containing markdown formatted text and returns a std::string containing html formatted text.',
        'Sure, here\'s a C++ function that takes a reference to a std::string containing Markdown formatted text and returns a std::string containing HTML formatted text:\n\n```\n#include <string>\n\nstd::string markdownToHtml(std::string& markdown) {\n    std::string html = markdown;\n\n    // Replace headers\n    html = std::regex_replace(html, std::regex("^# (.*)"), "<h1>$1</h1>");\n    html = std::regex_replace(html, std::regex("^## (.*)"), "<h2>$1</h2>");\n    html = std::regex_replace(html, std::regex("^### (.*)"), "<h3>$1</h3>");\n    html = std::regex_replace(html, std::regex("^#### (.*)"), "<h4>$1</h4>");\n    html = std::regex_replace(html, std::regex("^##### (.*)"), "<h5>$',
        21],
       ['Can you explain to me how the stable diffusion algorithm for ai generated images can be used to enhance the visual quality of low resolution and low quality images? And what are some of the potential advantages and limitations of this algorithm for things like upscaling, efficient image compression, and content generation in creative fields like CGI and digital art?',
        'Sure! The Stable Diffusion Algorithm is a machine learning technique that can be used to enhance the visual quality of low resolution and low quality images. The algorithm works by progressively adding noise to an input image and then removing the noise to generate a new image that has a higher resolution and visual quality. The noise is added and removed in a series of steps, or "diffusions," which gradually refine the image.\n\nOne advantage of the Stable Diffusion Algorithm is that it can be used for upscaling low resolution images. By adding noise and then removing it in a series of diffusions, the algorithm can create a new image that is higher in resolution than the original image. This can be useful for enhancing the visual quality of images in a variety of applications, such as medical imaging, surveillance, and satellite imagery.\n\nAnother advantage of the algorithm is that it can be used for efficient image compression. The algorithm works by',
        28],
       ['Can you explain to me how the stable diffusion algorithm for ai generated images can be used to enhance the visual quality of low resolution and low quality images? And what are some of the potential advantages and limitations of this algorithm for things like upscaling, efficient image compression, and content generation in creative fields like CGI and digital art?',
        'Sure! The Stable Diffusion Algorithm is a machine learning technique that can be used to enhance the visual quality of low resolution and low quality images. The algorithm works by progressively adding noise to an input image and then removing the noise to generate a new image that has a higher resolution and visual quality. The noise is added and removed in a series of steps, or "diffusions," which gradually refine the image.\n\nOne advantage of the Stable Diffusion Algorithm is that it can be used for upscaling low resolution images. By adding noise and then removing it in a series of diffusions, the algorithm can create a new image that is higher in resolution than the original image. This can be useful for enhancing the visual quality of images in a variety of applications, such as medical imaging, surveillance, and satellite imagery.\n\nAnother advantage of the algorithm is that it can be used for efficient image compression. The algorithm works by',
        28],
       ['Famously, some spy-satellites from the KeyHole series developed and operated by the US National Reconnaissance Office, where similar in capabilities to the Hubble Space Telescope, but then pointed at the earth rather than out into the universe. What can you tell me about these satellites? What era were they developed? Are they still active, and what are their approximate capabilities thought to be?',
        'The KeyHole series of spy satellites were developed and operated by the US National Reconnaissance Office. They were similar in capabilities to the Hubble Space Telescope, but instead of looking out into the universe, they were aimed at the Earth. These satellites were developed in an era when advancements in space technology were allowing for greater surveillance capabilities from orbit. It is unclear if they are still active today, but their capabilities were thought to include high-resolution imaging and possibly signals intelligence.',
        33]], dtype=object)

In [7]:
from collections import Counter
import numpy as np

def diversity(tokens):
    if len(tokens) <= 1:
        return np.nan
    return len(Counter(tokens).keys()) / float(len(tokens))

data['diversity'] = data.assistant_prompt.apply(lambda x: diversity(x.lower().split()))

NameError: name 'data' is not defined

In [51]:
data.diversity.describe()

count    167.000000
mean       0.614723
std        0.202712
min        0.068452
25%        0.479592
50%        0.603352
75%        0.768067
max        1.000000
Name: diversity, dtype: float64

In [52]:
data.sort_values(by='diversity')[['assistant_prompt', 'diversity']].dropna(subset=['diversity']).tail(5).values

array([["I'll do my best.", 1.0],
       ["You're welcome! Let me know if anything else I can do.", 1.0],
       ['Sure! If you need advice on any specific topic, feel free to ask me.',
        1.0],
       ['Met on a train are you?', 1.0],
       ['What city in the world are you currently living in?', 1.0]],
      dtype=object)

In [54]:
scores[0].corr(data.LCS), scores[0].corr(data.diversity), data.LCS.corr(data.diversity), scores[0].corr(data.LCS * data.diversity), scores[0].corr(data.LCS + data.diversity)

(0.0280468411440579,
 0.23634444797734666,
 0.37284523566387207,
 0.0612667349098726,
 0.19177762151322653)

In [172]:
sizes = ['160m', '410m', '1.4b', '2.8b', '6.9b']
dsts = ['dolly', 'oasst1', 'sharegpt']
chkpt = ['base', 'final']

def analysis(sz, ck, ds): 
    df = pd.read_pickle(f'/workspaces/lit-gpt/out/inference/pythia-{sz}-deduped-{ds}-{ck}-eval.pkl')
    data = pd.read_json(f'/workspaces/lit-gpt/out/inference/pythia-{sz}-deduped-{ds}-{ck}-eval.json')

    data = pd.merge(data, df, how='left', left_on='assistant_prompt', right_on='output')

    return [
        data.apply(lambda row: mylcs(row.user_prompt.lower().split(), row.assistant_prompt.lower().split()), axis=1).mean(), 
        data.apply(lambda row: mylcs(row.user_prompt.lower().split(), row.label.lower().split()), axis=1).mean(), 
        data.assistant_prompt.apply(lambda x: diversity(x.lower().split())).dropna().mean(),
        data.label.apply(lambda x: diversity(x.lower().split())).dropna().mean()
    ]

pd.DataFrame([[ds, sz, ck] + analysis(sz, ck, ds) for ds in dsts for sz in sizes for ck in chkpt], columns=['ds', 'sz', 'ck', 'overlap', 'overlap_gold', 'diversity', 'diversity_gold'])

FileNotFoundError: File /workspaces/lit-gpt/out/inference/pythia-160m-deduped-sharegpt-base-eval.json does not exist

In [187]:
labels = pd.read_pickle(f'/workspaces/lit-gpt/out/inference/pythia-160m-deduped-dolly-base-eval.pkl')

In [188]:
data_base = pd.read_json('/workspaces/lit-gpt/out/inference/pythia-160m-deduped-dolly-base-eval.json')
scores_base = data_base.score.apply(pd.Series).stack().str.split('/').apply(pd.Series)[0].str.strip().replace({'n':'None'}).apply(eval).unstack()

data_final = pd.read_json('/workspaces/lit-gpt/out/inference/pythia-160m-deduped-dolly-final-eval.json')
scores_final = data_final.score.apply(pd.Series).stack().str.split('/').apply(pd.Series)[0].str.strip().replace({'n':'None'}).apply(eval).unstack()

In [189]:
data_base = data_base.join(scores_base, how='left')
data_final = data_final.join(scores_final, how='left')

In [190]:
data = pd.concat([data_base, data_final])[['user_prompt', 'assistant_prompt', 0, 1, 2, 3]]

In [191]:
data = pd.merge(data, labels, left_on='user_prompt', right_on='input')

In [192]:
data['overlap'] = data.apply(lambda row: mylcs(row.user_prompt.lower().split(), row.assistant_prompt.lower().split()), axis=1)
data['overlap_gold'] = data.apply(lambda row: mylcs(row.user_prompt.lower().split(), row.label.lower().split()), axis=1)
data['diversity'] = data.assistant_prompt.apply(lambda x: diversity(x.lower().split())).dropna()
data['diversity_gold'] = data.label.apply(lambda x: diversity(x.lower().split())).dropna()

In [193]:
data = data[['overlap', 'diversity', 0]].dropna()

In [194]:
X, y = data[['overlap', 'diversity']].values, data[0].values
y = (y - y.mean()) / y.std()

In [195]:
from sklearn.linear_model import LinearRegression

In [196]:
clf = LinearRegression().fit(X, y)

In [197]:
clf.score(X, y)

0.46487371401705624

In [198]:
import statsmodels.api as sm
import numpy as np

X = sm.add_constant(X)
# Create and fit the OLS model
model = sm.OLS(y, X)
results = model.fit()

# Print the summary, which includes the F-statistic and its p-value
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.465
Model:                            OLS   Adj. R-squared:                  0.460
Method:                 Least Squares   F-statistic:                     97.30
Date:                Sat, 20 Sep 2025   Prob (F-statistic):           3.86e-31
Time:                        00:15:55   Log-Likelihood:                -251.13
No. Observations:                 227   AIC:                             508.3
Df Residuals:                     224   BIC:                             518.5
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.6347      0.080     -7.923      0.000      -0.793      -0.477
x1             2.4118      0.408      5.910      0.000       1.608       3.216
x2             1.1467      0.219      5.237      0.000       0.715       1.578
==============================================================================
Omnibus:                       69.721   Durbin-Watson:                   2.004
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              483.181
Skew:                           0.984   Prob(JB):                    1.20e-105
Kurtosis:                       9.871   Cond. No.                         9.69
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [98]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (2.3.3)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (1.16.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (2.3.1)
Collecting patsy>=0.5.6 (from statsmodels)
  Downloading patsy-1.0.1-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: packaging>=21.3 in /home/codespace/.local/lib/python3.12/site-packages (from statsmodels) (24.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/codespace/.local/lib/python3.12/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/codespace/.local/lib/python3.12/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)
Downloading statsmodels-0.14.5-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 24.5 MB/s eta 0:00:0000:010:01
Downloading patsy-1.0.1-py2.py3-none-any.whl (232 kB)
Installing collected packages: patsy, statsmodels
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [statsmodels] [statsmodels]
Successfully installed patsy-1.0.1 statsmodels-0.14.5

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python3 -m pip install --upgrade pip